services:
  directus:
    build: .
    ports:
      - '8055:8055'
    volumes:
      # Mount the data.db to persist data
      - ./data.db:/directus/database/data.db
    environment:
      KEY: 'directus-extension-demo-key'
      SECRET: 'directus-extension-demo-secret'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'admin'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      # Enable extensions auto-reload
      EXTENSIONS_AUTO_RELOAD: 'true'
      # Bật log để dễ debug
      LOG_LEVEL: 'info'
